# Copyright 2022 Research G.K.

# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "15:00"
      timezone: "Asia/Tokyo"
